export const ANIMATION = {
  SWIPE_DURATION: 300,        

  ROTATION_MULTIPLIER_X: 0.015,  
  ROTATION_MULTIPLIER_Y: 120,
  SWIPE_THRESHOLD: 120,
  VELOCITY_THRESHOLD: 0.7,
};

export const STACK = {
  MAX_VISIBLE: 5,                 
  SCALE_DENOMINATOR: 20,
  TRANSLATE_Y_MULTIPLIER: 30,
  OPACITY_DENOMINATOR: 10,
};

